### ISSUE TITLE
Issue with running `docker run` for integration testing

### ISSUE THREAD

**Issue by chenrui333** [summerwind/actions-runner-controller#32] opened 2020-04-14 05:46 UTC
I have run into some issue with running `docker run xx-image` after moving some of the workflow into self-hosted runner. I could not figure it out, but feel it might be helpful to post in here and discuss.

The flow looks like something below:
```
docker run -it --rm \
	-v $(PWD):/local \
	xx-image:latest \
	/local/e2e.sh
```

The error log that i keep getting:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/local/e2e.sh\": stat /local/e2e.sh: no such file or directory": unknown.
```

While it works before, I suspect it might be related to the `dind` docker image it used for the runner. Does the dind docker engine impact the volume mount?? 

Please shed some insight on fixing the issue and let me know if this makes sense. Thanks!!

**Comment by mumoshu** [comment] 2020-04-14 07:07
@chenrui333 Ah yes, the dind container and the runner container needs explicit volume & volume mounts configured for that to work.

Could you configure `spec.volumes` and `spec.volumeMounts` appropriately in your runner/runnerreplicaset/runnerdeployment spec?

If you could share me a few examples of paths returned by `$(PWD)`, I can guide you how you should configure volumes/volumeMounts.

FYI, the mapping between the runner spec and the runner pod volumes/mounts is implemented in https://github.com/summerwind/actions-runner-controller/blob/b8b4ef4b60a45fe647a19a6f56130eb3449a9a99/controllers/runner_controller.go#L416.

**Comment by chenrui333** [comment] 2020-04-14 15:12
Let me check on my environment really quick, thanks for clarifying the mystery.

**Comment by chenrui333** [comment] 2020-04-15 13:31
@mumoshu any advice or do you need more info from my side?

**Comment by mumoshu** [comment] 2020-04-15 13:46
Ah, that's too bad. We can't share `/` between the runner container and the find container cuz it breaks both sides. We need to change either the runner side or your workflow to use another directory.

I thought it was `/github/workspace` in the managed GitHub Actions runner.

Would you mind running `find -maxdepth 3 /github/workspace` in your workflow to figure out what's in your workflow env currently?

Depending on that, we can perhaps change the runner container to create necessary directories and set proper workdir so that you can just mount $(PWD) to docker containers.

**Comment by chenrui333** [comment] 2020-04-15 14:10
I dont think I have `/github/workflow` path there.

Here is the debug output:
```
Run find -maxdepth 3 /github/workspace
  find -maxdepth 3 /github/workspace
  shell: /bin/bash -e {0}
find: paths must precede expression: `/github/workspace'
##[error]Process completed with exit code 1.
```

**Comment by chenrui333** [comment] 2020-04-15 14:33
@mumoshu

**Comment by chenrui333** [comment] 2020-04-15 23:18
Here are some env values that I found on the runner as well:

```
OLDPWD=/runner/bin
PWD=/runner
HOME=/home/runner
```

**Comment by chenrui333** [comment] 2020-04-15 23:45
@mumoshu this issue might be related to this?
`https://github.com/actions/runner/issues/406`

**Comment by mumoshu** [comment] 2020-04-16 11:20
@chenrui333 Thanks! That does help. I believe `./config.sh --work /home/github/work` is the key - I believe that it worth trying to update our Dockerfile to use `./config.sh --work /home/github/work --once` rather than `./config.sh --once` which we have today.

**Comment by chenrui333** [comment] 2020-04-16 12:41
Coo, let me do a quick check.

**Comment by chenrui333** [comment] 2020-04-16 14:53
This is the current setup:

```
cd /runner
./config.sh --unattended --replace --name "${RUNNER_NAME}" --url "https://github.com/${RUNNER_REPO}" --token "${RUNNER_TOKEN}"

unset RUNNER_NAME RUNNER_REPO RUNNER_TOKEN
exec ./run.sh --once
```

So I should update `./config.sh` to include work option?

**Comment by mumoshu** [comment] 2020-04-16 23:38
@chenrui333 Ah yes you're absolutely correct! In my previous comment, I was confusing between config.sh and run.sh.

**Comment by chenrui333** [comment] 2020-04-17 23:02
Still having the same error message:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/local/e2e.sh\": stat /local/e2e.sh: no such file or directory": unknown.

**Comment by chenrui333** [comment] 2020-04-17 23:09
In my test PR, I am still seeing the same thing

```
Run find -maxdepth 3 /github/workspace
  find -maxdepth 3 /github/workspace
  shell: /bin/bash -e {0}
find: paths must precede expression: `/github/workspace'
##[error]Process completed with exit code 1.
```

**Comment by summerwind** [comment] 2020-04-18 14:12
@chenrui333 Let me confirm the details. Did you run the following `docker` command in GitHub Actions Workflow?

```
$ docker run -it --rm \
	-v $(PWD):/local \
	xx-image:latest \
	/local/e2e.sh
```

If so, what kind of output do you get if you run the following command in the same GitHub Actions workflow?

```
$ ls -al 
$ echo $PWD
```

**Comment by chenrui333** [comment] 2020-04-18 19:10
@summerwind this is what I have got
```
drwxr-xr-x  4 runner root  145 Apr 18 18:48 .
drwxr-xr-x 61 runner root 4096 Apr 18 18:48 ..
-rw-r--r--  1 runner root    6 Apr 18 18:48 .python-version
-rw-r--r--  1 runner root 1631 Apr 18 18:48 BUILD
-rw-r--r--  1 runner root 1041 Apr 18 18:48 Dockerfile
-rw-r--r--  1 runner root 7340 Apr 18 18:48 Makefile
-rw-r--r--  1 runner root 2793 Apr 18 18:48 README.md
-rwxr-xr-x  1 runner root 1367 Apr 18 18:48 e2e.sh
drwxr-xr-x  3 runner root   47 Apr 18 18:48 infra
-rwxr-xr-x  1 runner root  986 Apr 18 18:48 run.sh
drwxr-xr-x  3 runner root   18 Apr 18 18:48 src
/runner/_work/meetup/meetup/modules/api-server
```

**Comment by summerwind** [comment] 2020-04-19 07:07
This problem was reproduced in my environment.

The problem is that `dockerd` is running in a sidecar and the volume mount (the `-v` option) does not work as intended because files are not shared between containers.

Let me consider a good solution to solve this problem.

**Comment by mumoshu** [comment] 2020-04-19 10:26
@summerwind Thanks for taking look into this!

I was wondering if this is where local persistent volumes shine.

**Comment by chenrui333** [comment] 2020-04-20 13:48
Thanks @summerwind!

**Comment by summerwind** [comment] 2020-04-21 03:42
I created PR #40 to try and figure out how to combine the runner and docker containers into one. Feedbacks are welcome!

**Comment by summerwind** [comment] 2020-04-25 01:09
Reopen this due to accidentally closed.

**Comment by summerwind** [comment] 2020-04-26 01:43
Fixed in #45 and v0.4.3 by sharing working directory between runner and docker container.
https://github.com/summerwind/actions-runner-controller/releases/tag/v0.4.3

**Comment by summerwind** [comment] 2020-04-29 02:18
I'm going to close this, but feel free to reopen if this is still an issue

**Closed by summerwind** 2020-04-29 02:18 UTC

**Comment by chenrui333** [comment] 2020-04-29 03:09
Sure, sounds good!
